name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Django image
      uses: docker/build-push-action@v2
      with:
        context: ./bookapi
        file: ./bookapi/Dockerfile
        push: true
        tags: ghcr.io/hilyas/bookapi:latest

    - name: Build and push React image
      uses: docker/build-push-action@v2
      with:
        context: ./bookfrontend
        file: ./bookfrontend/Dockerfile
        push: true
        tags: ghcr.io/hilyas/bookfrontend:latest
