name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push books image
      uses: docker/build-push-action@v2
      with:
        context: ./apps/books
        file: ./apps/books/Dockerfile
        push: true
        tags: ghcr.io/hilyas/books:latest
    
    # - name: Build and push sis image
    #   uses: docker/build-push-action@v2
    #   with:
    #     context: ./apps/sis
    #     file: ./apps/sis/Dockerfile
    #     push: true
    #     tags: ghcr.io/hilyas/sis:latest
